### ISSUE TITLE
it discloses error in the Testing model part as TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by rolrolis18** [pitsios-s/SVHN#1]
Hi, I did run the file and it discloses the next error in the "Test the model by measuring it's accuracy", it performs the first operations properly (I did set the iterations = 3000 to check if it was ok before doing the full 50000 iterations:

Step:      1, Training Accuracy: 0.080000, Batch Loss: 13.509691
Step:   1000, Training Accuracy: 0.920000, Batch Loss: 0.334041
Step:   2000, Training Accuracy: 0.840000, Batch Loss: 0.524482
Step:   3000, Training Accuracy: 0.820000, Batch Loss: 0.712740
Traceback (most recent call last):
  File "cnn.py", line 153, in <module>
    for i in range(test_iterations):
TypeError: 'float' object cannot be interpreted as an integer

Do you have an updated file?

Regards,

**Comment by pitsios-s** [comment]
Hi there,

The culprit actually lies in line 150 `test_iterations = svhn.test_examples / batch_size + 1`. The project was built using python 2.7, which always performs an integer division when dividing two integers. On the contrary, python 3+ applies true division which may result in a float number, thus the for loop can't run.

I suggest you are using python 3 and that's why you are getting this error. In this case I recommend to switch to python 2.7, or change the division operator from / to //
